---
- name: Local Download JDK
  local_action:
    module: get_url
    url: https://javadl.oracle.com/webapps/download/GetFile/1.8.0_181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/windows-i586/server-jre-8u181-windows-x64.tar.gz
    dest: /tmp/jdk-8u181-windows-x64.tar.gz
    checksum: sha256:7799b9007760663da32a3b177a0b9ea42ec268afaa69dcf8518cdce5136c3768
    force: true
    headers:
      Cookie: oraclelicense=a
- name: Local Extract JDK
  local_action:
    module: unarchive
    src: /tmp/jdk-8u181-windows-x64.tar.gz
    dest: /tmp/
- name: Copy JDK
  win_copy:
    src: /tmp/jdk1.8.0_181
    dest: C:\
    force: yes
- name: Set JAVA_HOME
  win_environment:
    name: JAVA_HOME
    value: C:\jdk1.8.0_181
    level: machine
    state: present
