---
- name: Download gcloud SDK
  # Using the versioned archives since it allows one to install a specific version
  # See: https://cloud.google.com/sdk/docs/downloads-versioned-archives
  win_get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-449.0.0-windows-x86_64-bundled-python.zip
    checksum: 052a0da7ce27dd6e941eaf1a56ec155dd39d2f3941070a2dfc2116ef2fc793ac
    checksum_algorithm: sha256
    dest: C:\Windows\Temp\gcloud.zip
- name: Extract gcloud SDK
  win_shell: Expand-Archive -Path C:\Windows\Temp\gcloud.zip -DestinationPath C:\
- name: Install gcloud SDK
  win_shell: C:\google-cloud-sdk\install.bat --quiet
- name: Add gcloud SDK to PATH
  win_path:
    elements: C:\google-cloud-sdk\bin
