export const CONFIGURATION_TABS = {
  PROPAGATION: 'propagation',
  PAYLOADS: 'payloads',
  CREDENTIALS_COLLECTORS: 'credentials_collectors',
  MASQUERADE: 'masquerade',
  POLYMORPHISM: 'polymorphism',
  ADVANCED: 'advanced'
};

const CONFIGURATION_TABS_ORDER = [
  CONFIGURATION_TABS.PROPAGATION,
  CONFIGURATION_TABS.PAYLOADS,
  CONFIGURATION_TABS.CREDENTIALS_COLLECTORS,
  CONFIGURATION_TABS.MASQUERADE,
  CONFIGURATION_TABS.POLYMORPHISM,
  CONFIGURATION_TABS.ADVANCED
];

export default CONFIGURATION_TABS_ORDER;
