#!/bin/bash

MONKEY_FOLDER=/var/monkey
INSTALLATION_FOLDER=/var/monkey/monkey_island/installation
PYTHON_FOLDER=/var/monkey/monkey_island/bin/python

# Prepare python virtualenv
pip3 install virtualenv --no-index --find-links file://$INSTALLATION_FOLDER
python3 -m virtualenv -p python3 ${PYTHON_FOLDER}

# install pip requirements
${PYTHON_FOLDER}/bin/python -m pip install -r $MONKEY_FOLDER/monkey_island/requirements.txt --no-index --find-links file://$INSTALLATION_FOLDER

# remove installation folder and unnecessary files
rm -rf ${INSTALLATION_FOLDER}
rm -f ${MONKEY_FOLDER}/monkey_island/requirements.txt

if [ -d "/etc/systemd/network" ]; then
    cp ${MONKEY_FOLDER}/monkey_island/service/systemd/*.service /lib/systemd/system/
    chmod +x ${MONKEY_FOLDER}/monkey_island/service/systemd/start_server.sh
    systemctl daemon-reload
    systemctl enable monkey-island
fi

${MONKEY_FOLDER}/monkey_island/create_certificate.sh ${MONKEY_FOLDER}/monkey_island/

service monkey-island start

echo Monkey Island installation ended

exit 0