#!/bin/sh

service monkey-island stop || true

rm -f /etc/init/monkey-island.conf
[ -f "/lib/systemd/system/monkey-island.service" ] && rm -f /lib/systemd/system/monkey-island.service

rm -r -f /var/monkey

exit 0