default_stages: [commit]
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [dlint==0.14.1]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: "envs/monkey_zoo/blackbox/expected_credentials.py"
      - id: end-of-file-fixer
        exclude: "envs/monkey_zoo/packer/files/mssql/ConfigurationFile.ini"
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/eslint/eslint
    rev: v8.35.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies: [typescript]
        args:
          [
            "monkey/monkey_island/cc/ui/src/",
            "monkey/monkey_island/cc/next_ui/src/",
            "--fix",
            "--max-warnings=0",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies:
          [
            types-ipaddress,
            types-paramiko,
            types-python-dateutil,
            types-pytz,
            types-PyYAML,
            types-requests,
          ]
        exclude: "vulture_allowlist.py"
        args: [--ignore-missing-imports, --check-untyped-defs]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "cd monkey && pytest"
        language: system
        files: "monkey/"
        exclude: "monkey/monkey_island/cc/ui"
        stages: [push]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
  - repo: https://github.com/mssalvatore/merge-issue-number-hook
    rev: v1.0.0
    hooks:
      - id: merge-issue-number
