from monkeytypes import (
    AgentID,
    DiscoveredService,
    FileExtension,
    HardwareID,
    IntRange,
    JSONSerializable,
    MachineID,
    NetworkPort,
    NetworkProtocol,
    NetworkService,
    NonNegativeFloat,
    Percent,
    PercentLimited,
    PortStatus,
)
