#!/bin/bash

INSTALLATION_FOLDER=/var/monkey_island/installation

# install pip requirements
pip install -r /var/monkey_island/pip_requirements.txt --no-index --find-links file://$INSTALLATION_FOLDER

# remove installation folder
rm -rf $INSTALLATION_FOLDER
