#!/bin/sh

service monkey-island stop || true
service monkey-mongo stop || true

rm -f /etc/init/monkey-island.conf
rm -f /etc/init/monkey-mongo.conf
rm /lib/systemd/system/monkey-island.service
rm /lib/systemd/system/monkey-mongo.service