GCP_TEST_MACHINE_LIST = {
    "europe-west3-a": [
        "sshkeys-11",
        "sshkeys-12",
        "hadoop-2",
        "hadoop-3",
        "mssql-16",
        "mimikatz-14",
        "mimikatz-15",
        "tunneling-9",
        "tunneling-10",
        "tunneling-11",
        "tunneling-12",
        "zerologon-25",
    ],
    "europe-west1-b": [
        "powershell-3-45",
        "powershell-3-46",
        "powershell-3-47",
        "powershell-3-48",
        "log4j-logstash-55",
        "log4j-logstash-56",
        "log4j-solr-49",
        "log4j-solr-50",
        "log4j-tomcat-51",
        "log4j-tomcat-52",
    ],
}
