from .hard_coded_credential_collector_schemas import HARD_CODED_CREDENTIAL_COLLECTOR_SCHEMAS
from .hard_coded_exploiter_schemas import HARD_CODED_EXPLOITER_SCHEMAS
from .hard_coded_fingerprinter_schemas import HARD_CODED_FINGERPRINTER_SCHEMAS
from .hard_coded_payloads_schemas import HARD_CODED_PAYLOADS_SCHEMAS
