#! /bin/bash

# Export APPRUN if running from an extracted image
self="$(readlink -f -- $0)"
here="${self%/*}"
APPDIR="${APPDIR:-${here}}"

# Export SSL certificate
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

if [ "$1" == "service" ] ; then
    exec /bin/bash "${APPDIR}/install-infection-monkey-service.sh" ${@:2}
fi


# Check if running as root
if [ $(id -u) -eq 0 ]; then
    echo "Warning: running as root is not recommended. You should instead run the AppImage as a regular user."
    echo "If you want to run the Agent as root, do so by choosing manual run mode."
else
    # Prompt to allow capabilities to open port < 1024
    echo "Adding permission for Infection Monkey to open port < 1024. By default the UI is served on port 443."
    sudo setcap 'cap_net_bind_service=+ep' "${APPIMAGE}"
    echo "Capabilities added, re-run the AppImage."
    exit 0
fi

# Call the entry point
for opt in "$@"
do
    [ "${opt:0:1}" != "-" ] && break
    if [[ "${opt}" =~ "I" ]] || [[ "${opt}" =~ "E" ]]; then
        # Environment variables are disabled ($PYTHONHOME). Let's run in a safe
        # mode from the raw Python binary inside the AppImage
        "$APPDIR/opt/python3.11/bin/python3.11" "$@"
        exit "$?"
    fi
done

export PYTHONNOUSERSITE=1
(PYTHONHOME="${APPDIR}/opt/python3.11" exec "${APPDIR}/opt/python3.11/bin/python3.11" "${APPDIR}/usr/src/monkey_island.py" $@)

exit "$?"
