class TelemCategoryEnum:
    ATTACK = "attack"
    AWS_INFO = "aws_info"
    CREDENTIALS = "credentials"
    EXPLOIT = "exploit"
    FILE_ENCRYPTION = "file_encryption"
    POST_BREACH = "post_breach"
    SCAN = "scan"
    STATE = "state"
    TRACE = "trace"
