class TelemCategoryEnum:
    EXPLOIT = "exploit"
    POST_BREACH = "post_breach"
    SCAN = "scan"
    SCOUTSUITE = "scoutsuite"
    STATE = "state"
    SYSTEM_INFO = "system_info"
    TRACE = "trace"
    TUNNEL = "tunnel"
    ATTACK = "attack"
    FILE_ENCRYPTION = "file_encryption"
