#!/bin/bash

MONKEY_FOLDER=/var/monkey
INSTALLATION_FOLDER=/var/monkey/monkey_island/installation
PYTHON_FOLDER=/var/monkey/monkey_island/bin/python
PYTHON_VERSION=python3.7

# Prepare python virtualenv
# This is using the apt package `python3.7-venv` which is listed in the `control` file as a dependency.
# See https://packages.debian.org/stable/python/python3.7-venv
$PYTHON_VERSION -m venv ${PYTHON_FOLDER}

# install pip requirements
${PYTHON_FOLDER}/bin/python -m pip install -r $MONKEY_FOLDER/monkey_island/requirements.txt --no-index --find-links file://$INSTALLATION_FOLDER

# remove installation folder and unnecessary files
rm -rf ${INSTALLATION_FOLDER}
rm -f ${MONKEY_FOLDER}/monkey_island/requirements.txt

${MONKEY_FOLDER}/monkey_island/install_mongo.sh ${MONKEY_FOLDER}/monkey_island/bin/mongodb

if [ -d "/etc/systemd/network" ]; then
    cp ${MONKEY_FOLDER}/monkey_island/service/systemd/*.service /lib/systemd/system/
    chmod +x ${MONKEY_FOLDER}/monkey_island/service/systemd/start_server.sh
    systemctl daemon-reload
    systemctl enable monkey-mongo
    systemctl enable monkey-island
fi

${MONKEY_FOLDER}/monkey_island/create_certificate.sh ${MONKEY_FOLDER}/monkey_island/

service monkey-island start
service monkey-mongo start

echo Monkey Island installation ended

exit 0