#!/bin/bash

# See the "Depends" field of the control file for what packages this scripts depends on.
# Here are the explanations for the current deps:
# Dependency - Why is it required
## openssl - Server certificate generation
## python3.7-dev - Server runtime
## python3.7-venv - For creating virtual env to install all the server pip deps (don't want to pollute system python)
## python3-venv - python3.7-venv doesn't work without it since you need ensure-pip
## build-essential - for compiling python dependencies that don't come in a pre-compiled wheel, like `netifaces`

echo "Installing Monkey Island (Infection Monkey server)..."

MONKEY_FOLDER=/var/monkey
INSTALLATION_FOLDER=/var/monkey/monkey_island/installation
PYTHON_FOLDER=/var/monkey/monkey_island/bin/python
PYTHON_VERSION=python3.7

# Prepare python virtualenv
# This is using the apt package `python3.7-venv` which is listed in the `control` file as a dependency.
# See https://packages.debian.org/stable/python/python3.7-venv
echo "Using $(command -v $PYTHON_VERSION) as the base for virtualenv creation"
$PYTHON_VERSION -m venv ${PYTHON_FOLDER}
# shellcheck disable=SC1090
source ${PYTHON_FOLDER}/bin/activate

echo "Installing Python dependencies using $(command -v python) and $(command -v pip)..."
# First, make sure that pip is updated
python -m pip install --upgrade pip
# Then install the dependecies from the pre-downloaded whl and tar.gz file
python -m pip install -r $MONKEY_FOLDER/monkey_island/requirements.txt --no-index --find-links file://$INSTALLATION_FOLDER

deactivate

# remove installation folder and unnecessary files
rm -rf ${INSTALLATION_FOLDER}
rm -f ${MONKEY_FOLDER}/monkey_island/requirements.txt

echo "Installing mongodb..."
${MONKEY_FOLDER}/monkey_island/install_mongo.sh ${MONKEY_FOLDER}/monkey_island/bin/mongodb

if [ -d "/etc/systemd/network" ]; then
    cp ${MONKEY_FOLDER}/monkey_island/service/systemd/*.service /lib/systemd/system/
    chmod +x ${MONKEY_FOLDER}/monkey_island/service/systemd/start_server.sh
    systemctl daemon-reload
    systemctl enable monkey-mongo
    systemctl enable monkey-island
fi

echo "Creating server certificate..."
${MONKEY_FOLDER}/monkey_island/create_certificate.sh ${MONKEY_FOLDER}/monkey_island/cc

echo "Starting services..."
service monkey-island start
service monkey-mongo start

echo ""
echo "Monkey Island installation ended."
echo "The server should be accessible soon via https://<server_ip>:5000/"
echo "To check the Island's status, run 'sudo service monkey-island status'"
echo ""

exit 0
