#!/usr/bin/env bash
# Absolute monkey's path
MONKEY_FOLDER_NAME="infection_monkey"
# Url of public git repository that contains monkey's source code
MONKEY_GIT_URL="https://github.com/guardicore/monkey"

# Monkey binaries
LINUX_32_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/monkey-linux-32"
LINUX_32_BINARY_NAME_Latest="monkey-linux-32"
LINUX_64_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/monkey-linux-64"
LINUX_64_BINARY_NAME_Latest="monkey-linux-64"
WINDOWS_32_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/monkey-windows-32.exe"
WINDOWS_32_BINARY_NAME_Latest="monkey-windows-32.exe"
WINDOWS_64_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/monkey-windows-64.exe"
WINDOWS_64_BINARY_NAME_Latest="monkey-windows-64.exe"

# Other binaries for monkey

TRACEROUTE_64_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/traceroute64"
TRACEROUTE_32_BINARY_URL_Latest="https://github.com/guardicore/monkey/release/latest/download/traceroute32"
SAMBACRY_64_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/sc_monkey_runner64.so"
SAMBACRY_32_BINARY_URL_Latest="https://github.com/guardicore/monkey/releases/latest/download/sc_monkey_runner32.so"


