---
- name: Create a new user and allow RDP access
  hosts: all
  vars:
    ansible_remote_tmp: C:\Windows\Temp
  tasks:
    - name: Create user
      win_user:
        name: m0nk3y
        password: S3Cr3T1#
        password_never_expires: yes
        state: present
        update_password: on_create
        groups_action: add
        groups:
          - Administrators
          - "Remote Desktop Users"

    - name: Add disablerestrictedadmin key to enable Restricted Admin mode
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Lsa
        name: DisableRestrictedAdmin
        data: 0
        type: dword

    - name: Change the hostname to rdp-65
      ansible.windows.win_hostname:
        name: rdp-65
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
