---
- name: Create a mimikatz-14 machine image
  hosts: all
  become_method: runas
  vars:
    ansible_remote_tmp: C:\Windows\Temp
    ansible_become_password: Ivrrw5zEzs
  tasks:
    - name: Create user
      win_user:
        name: m0nk3y
        password: Ivrrw5zEzs
        password_never_expires: yes
        state: present
        update_password: on_create
        groups_action: add
        groups:
          - Administrators
          - "Remote Desktop Users"

    - name: Allow port 445 SMB
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Port 445" dir=in action=allow protocol=TCP localport=445

    - name: Allow port 135 DCOM
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Port 135" dir=in action=allow protocol=TCP localport=135

    - name: Allow DCOM Connection
      win_firewall_rule:
        name: Allow DCOM Connection
        localport: any
        direction: in
        program: C:\Windows\System32\svchost.exe
        action: allow
        state: present
        enabled: yes

    - name: Disable Windows Defender using registry
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        data: 1
        type: dword
        state: present

    - name: Disable Windows Defender
      win_shell: Set-MpPreference -DisableIntrusionPreventionSystem $true -DisableIOAVProtection $true -DisableRealtimeMonitoring $true -EnableNetworkProtection AuditMode -Force
      become: yes
      become_user: m0nk3y

    - name: Create a generic credential for mimikatz-15
      win_credential:
        name: 10.2.2.15
        type: generic_password
        username: m0nk3y
        secret: pAJfG56JX><
        state: present
      become: yes
      become_user: m0nk3y

    - name: Change the hostname to mimikatz-14
      ansible.windows.win_hostname:
        name: mimikatz-14
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - import_tasks: tasks/windows_disable_powershell_remoting.yml

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
