---
- name: Create a new user and allow RDP access
  hosts: all
  become_method: runas
  vars:
    ansible_remote_tmp: C:\Windows\Temp
    ansible_become_password: P@ssw0rd!
  tasks:
    - name: Create user
      win_user:
        name: m0nk3y
        password: P@ssw0rd!
        password_never_expires: yes
        state: present
        update_password: on_create
        groups_action: add
        groups:
          - Administrators
          - "Remote Desktop Users"

    - name: Allow port 8080
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Port 8080" dir=in action=allow protocol=TCP localport=8080

    - name: Disable Windows Defender using registry
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        data: 1
        type: dword
        state: present

    - name: Disable Windows Defender
      win_shell: Set-MpPreference -DisableIntrusionPreventionSystem $true -DisableIOAVProtection $true -DisableRealtimeMonitoring $true -EnableNetworkProtection AuditMode -Force
      become: yes
      become_user: m0nk3y

    - name: Change the hostname to rdp-64
      ansible.windows.win_hostname:
        name: rdp-64
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
