---
- name: Create a new user and allow RDP access
  hosts: all
  become_method: runas
  vars:
    host_name: rdp-64
    user_name: m0nk3y
    user_password: P@ssw0rd!
    ansible_remote_tmp: C:\Windows\Temp
    ansible_become_password: P@ssw0rd!
  tasks:
    - import_tasks: tasks/windows_create_user.yml
      vars:
        username: "{{ user_name }}"
        password: "{{ user_password }}"
        user_groups: [Administrators, "Remote Desktop Users"]
    - import_tasks: tasks/windows_disable_automatic_updates.yml
    - import_tasks: tasks/windows_disable_windows_defender.yml

    - name: Allow port 8080
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Port 8080" dir=in action=allow protocol=TCP localport=8080

    # Disallow PowerShell to this machine from internal ips
    - import_tasks: tasks/windows_disallow_powershell_remoting_on_subnet.yml
      vars:
        subnet_ip: "10.2.0.0/16"

    - name: Change the hostname to {{ host_name }}
      ansible.windows.win_hostname:
        name: "{{ host_name }}"
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
