---
- name: Create a new user and allow RDP access
  hosts: all
  vars:
    ansible_remote_tmp: C:\Windows\Temp
  tasks:
    - name: Create user
      win_user:
        name: m0nk3y
        password: P@ssw0rd!
        password_never_expires: yes
        state: present
        update_password: on_create
        groups_action: add
        groups:
          - Administrators
          - "Remote Desktop Users"

    - name: Allow port 8080
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Port 8080" dir=in action=allow protocol=TCP localport=8080

    - name: Change the hostname to rdp-64
      ansible.windows.win_hostname:
        name: rdp-64
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
