---
- name: Create a new user and allow RDP access
  hosts: all
  vars:
    host_name: rdp-65
    user_name: m0nk3y
    user_password: S3Cr3T1#
    ansible_remote_tmp: C:\Windows\Temp
    ansible_become_password: S3Cr3T1#
  tasks:
    - import_tasks: tasks/windows_create_user.yml
      vars:
        username: "{{ user_name }}"
        password: "{{ user_password }}"
        user_groups: [Administrators, "Remote Desktop Users"]
    - import_tasks: tasks/windows_disable_automatic_updates.yml
    - import_tasks: tasks/windows_disable_windows_defender.yml

    # This is done so we can use NT hash to RDP to the machine
    - name: Add disablerestrictedadmin key to enable Restricted Admin mode
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Lsa
        name: DisableRestrictedAdmin
        data: 0
        type: dword

    # Disallow PowerShell to this machine from internal ips
    - import_tasks: tasks/windows_disallow_powershell_remoting_on_subnet.yml
      vars:
        subnet_ip: "10.2.0.0/16"

    - name: Change the hostname to {{ host_name }}
      ansible.windows.win_hostname:
        name: "{{ host_name }}"
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
