---
- name: Configure chrome credential files on Linux
  hosts: all
  remote_user: root

  tasks:
  - name: Add user
    user:
        name: m0nk3y
        password: "{{ 'password' | password_hash('sha512') }}"
  - name: Create chromimum data directory
    file:
      path: /home/m0nk3y/snap/chromium/common/chromium
      state: directory
  - name: Copy local state
    copy:
        src: data/
        dest: /home/m0nk3y/snap/chromium/common/chromium/
        owner: m0nk3y
        group: m0nk3y
        mode: 0600
  - name: Rename local state file
    shell: mv /home/m0nk3y/snap/chromium/common/chromium/LocalState /home/m0nk3y/snap/chromium/common/chromium/Local\ State
  - name: Rename login database files
    # For some reason, ansible had trouble copying files with spaces
    # in the name, so we have to rename them.
    shell: |
      for d in /home/m0nk3y/snap/chromium/common/chromium/*/ ; do
        if [ -d "$d" ]; then
          mv "$d/LoginData" "$d/Login Data"
        fi
      done
  - name: Debug list dir
    command: ls -Rla /home/m0nk3y/snap/chromium/common/chromium/
    register: out
  - debug: var=out.stdout_lines

  # The machine needs some way of being accessed
  - name: Enable Password Authentication
    lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*no'
        line: "PasswordAuthentication yes"
        state: present
        backup: yes
  - name: Remove sshguard
    apt:
        name: sshguard
        state: absent
