---
- name: Create hadoop-3 machine image
  hosts: all
  vars:
    host_name: hadoop-3
  tasks:
    - import_tasks: tasks/windows_disable_automatic_updates.yml
    - import_tasks: tasks/windows_disable_windows_defender.yml
    - import_tasks: tasks/windows_install_7zip.yml
    - import_tasks: tasks/windows_install_java.yml
    - import_tasks: tasks/windows_install_hadoop.yml

    - name: Allow port 8088 Hadoop
      win_command:
        cmd: netsh advfirewall firewall add rule name="Allow Hadoop" dir=in action=allow protocol=TCP localport=8088

    # Disallow RDP to this machine from internal ips
    - import_tasks: tasks/windows_disallow_rdp_for_subnet.yml
      vars:
        subnet_ip: "10.2.0.0/16"

    # Disallow PowerShell to this machine from internal ips
    - import_tasks: tasks/windows_disallow_powershell_remoting_on_subnet.yml
      vars:
        subnet_ip: "10.2.0.0/16"

    - name: Change the hostname to {{ host_name }}
      ansible.windows.win_hostname:
        name: "{{ host_name }}"
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
