---
- name: Configure the Linux island
  hosts: all
  remote_user: root

  tasks:
    - import_tasks: tasks/linux_setup_docker.yml
    - import_tasks: tasks/linux_install_gcloud.yml
    - import_tasks: tasks/linux_install_python.yml
    - name: Enable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*no'
        line: "PasswordAuthentication yes"
        state: present
        backup: yes
    - name: Remove sshguard
      apt:
        name: sshguard
        state: absent
